### ISSUE TITLE
new features _ Chong

### ISSUE THREAD

**Issue by cgeng18** [robertisandor/USF-MSDS621-KaggleHomeDepot#2]
1)  counting how many "initial searching terms" could be found in the title/product description;
2)  stemming the "initial searching terms" as a new column "stemmed_terms", update all "clean_*" columns;
3)  lemmatizing the "initial searching terms" as a new column "lemmatize_terms", update all "clean_*" columns;

**Comment by robertisandor** [comment]
Features have been tested and integrated into the code. Thanks for your help!
