### ISSUE TITLE
Divya: Add more features

### ISSUE THREAD

**Issue by Divya-Bhargavi** [robertisandor/USF-MSDS621-KaggleHomeDepot#3]
1) Add functionality - Material , color, pieces, temperature
2) Add distance metrics - Levenshtein distance, Jaccard  distance 
between:
search term and title using several n-gram segmentations
search term and product description
search term and transposed attributes
3) Brand popularity
4) Count (English) stop words and spelling errors in the query

**Comment by robertisandor** [comment]
Features have been tested and integrated into the code. Thanks for your help!
